[[plugins]]
repo = 'preservim/nerdtree'
hook_add = '''
source $HOME/dotfiles/vim/plugins/nerdtree.rc.vim
'''

[[plugins]]
repo = 'editorconfig/editorconfig-vim'

[[plugins]]
repo = 'fatih/vim-go'
hook_add = '''
source $HOME/dotfiles/vim/plugins/vim-go.rc.vim
'''
